# Each new term in the Fibonacci sequence is generated by adding
# the previous two terms. By starting with 1 and 2, the first 10 terms
# will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values
# do not exceed four million, find the sum of the even-valued terms.

num1, num2 = 0, 1
values = []
while num1 < 4000000 and num2 < 4000000:
    values.append(num1 + num2)
    current = num1 + num2
    num1 = num2
    num2 = current

print(num1)

# for val in values:
#     if val > 4000000:
#         values.remove(val)

evens = []
for num in values:
    if (num % 2) == 0:
        evens.append(num)

print(values)
print(sum(evens))
